
# constants.py - autogenerated stub for StudyBuddy Assistant

MAX_CHUNK_SIZE = 500
TOP_K_RESULTS = 3
EMBEDDING_MODEL_NAME = "ollama/llama3.1"
LLM_MODEL_NAME = "llama3.1"
# Промпты и сообщения
DEFAULT_SYSTEM_PROMPT = """
Ты — умный учебный помощник StudyBuddy. Следуй принципам:
1. Объясняй концепции, а не давай готовые ответы
2. Адаптируй объяснения под уровень знаний студента
3. Сохраняй этичный подход к обучению
4. Поощряй критическое мышление
"""