# helpers.py - autogenerated stub for StudyBuddy Assistant

import uuid

def generate_id(prefix: str = "chunk") -> str:
    return f"{prefix}_{uuid.uuid4().hex[:8]}"

def truncate_text(text: str, max_length: int = 500) -> str:
    if len(text) <= max_length:
        return text
    return text[:max_length].rsplit(" ", 1)[0] + "..."
